name: graphql
description: A stand-alone GraphQL client for Dart, bringing all the features from
  a modern GraphQL client to one easy to use package.
version: 4.0.1
homepage: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql
dependencies:
  hive: ^1.4.4+1
  http: ^0.13.1
  gql:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql
  gql_exec:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_exec
  gql_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_link
  gql_http_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_http_link
  gql_transform_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_transform_link
  gql_error_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_error_link
  gql_dedupe_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_dedupe_link
  normalize:
    git:
      url: git://github.com/julienzarka/ferry.git
      path: normalize
  collection: ^1.15.0
  websocket: ^0.0.5
  rxdart: ^0.26.0
  uuid_enhanced: ^3.0.2
dev_dependencies:
  pedantic: ^1.11.0
  mockito: ^4.1.4
  test: ^1.16.5
  test_coverage: ^0.5.0
  http_parser: ^4.0.0
environment:
  sdk: '>=2.6.0 <3.0.0'
