name: graphql_flutter
description: A GraphQL client for Flutter, bringing all the features from a modern GraphQL client to one easy to use package.
version: 4.1.0-beta.2
homepage: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql_flutter
dependencies:
  graphql:
    git:
      url: git://github.com/julienzarka/graphql-flutter.git
      path: packages/graphql
  gql_exec:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_exec
  flutter:
    sdk: flutter
  meta: ^1.3.0
  path_provider: ^2.0.1
  path: ^1.8.0
  connectivity: ^3.0.3
  hive: ^2.0.1
dev_dependencies:
  pedantic: ^1.11.0
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter
  http: ^0.13.1
environment:
  sdk: '>=2.10.0 <3.0.0'
